title: Prathyusha Challa
logo: /assets/img/logo.png
description: I am a product manger with over a decade of experience at multiple domains. I am a product thinker from users perspective always striving to create best user interface and user experience. Deriving product decisions through data driven approach and customer empathy had always helped me in delivering excellent products. i would like to envision myself to be a best team player and  a leader.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
